name: Poll Taostats Parser

on:
  workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest
    env:
      WS_URL: ${{ secrets.WS_URL }}
      POLL_INTERVAL: ${{ secrets.POLL_INTERVAL }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run taostats poller
        run: python src/main.py
