name: TAOStats Parser CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  parser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug: show repo layout
        run: ls -R .

      - name: Find and run TAOStats parser
        run: |
          # Автоматический поиск скрипта
          SCRIPT_PATH=$(find . -type f -name 'taostats_http_parser.py')
          if [ -z "$SCRIPT_PATH" ]; then
            echo "Error: taostats_http_parser.py not found"
            exit 1
          fi
          echo "Found parser at $SCRIPT_PATH"
          python "$SCRIPT_PATH"
